version: '2'
services:
  web:
    image: httpd:2.2.32
    container_name: httpd 
    ports:
      - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
