version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6.7
    container_name: elasticsearch
    volumes:
      - /var/lib/elasticsearch:/usr/share/elasticsearch/data
      - /var/log/elasticsearch:/usr/share/elasticsearch/logs
      - /etc/localtime:/etc/localtime
    ports:
      - '9200:9200'
    network_mode: 'host'
  kibana:
    container_name: kibana
    build: kibana/
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - '5601:5601'
    environment:
      - http_proxy=
      - https_proxy=
      - ELS_HOST=elasticsearch
    network_mode: 'host'
  fluentd:
    container_name: fluentd
    build: fluentd/
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    environment:
      - http_proxy=
      - https_proxy=
      - ELS_HOST=elasticsearch
    network_mode: 'host'
