version: '2'
services:
  nginx:
    container_name: nginx
    build: nginx/
    depends_on:
      - node_app
      - fluentd
    ports:
      - '80:80'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: fluentd:24224
        tag: docker.{{.FullID}}
    network_mode: 'host'
  node_app:
    container_name: node_app
    build: node_app/
    depends_on:
      - fluentd
    ports:
      - '8080:8080'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: fluentd:24224
        tag: docker.{{.FullID}}
    network_mode: 'host'
